Repository Shopify/rubocop-sorbet, pull requests merged in 2025-02, with the labels that each got.

#278 Upgrade Ruby to 3.4.1
  .github/workflows/ci.yml
  .ruby-version
Labels: chore

#282 Tweak Rubocop rules for inline RBS in RBI files
  config/rbi.yml
Labels: enhancement

#284 Add `ForbidTEnum` cop
  config/default.yml
  lib/rubocop/cop/sorbet/forbid_t_enum.rb
  lib/rubocop/cop/sorbet_cops.rb
  manual/cops.md
  manual/cops_sorbet.md
  spec/rubocop/cop/sorbet/forbid_t_enum_spec.rb
Labels: feature
